### PR TITLE
Make ZipArchiver work with Option instead of Some

### PR DESCRIPTION
**Pull request by jakobmerrild**
Requiring Some for the Size of ZipArchive makes it impossible to work with if you have streams of entries where you don't know the size up front (without reading all that data into memory).

### CODE REVIEW

**Comment by jakobmerrild** [comment]
@lhns If you prefer I can also parameterize `ZipArchive` over `Size[A] <: Option[A]` instead of making the `Size` contravariant for all `Archiver`s

**Comment by lhns** [comment]
That would actually be pretty cool because we could have a makeDeflated and makeStored constructor that returns ZipArchiver[F, Option] or ZipArchiver[F, Some].

**Comment by jakobmerrild** [comment]
I don't know if that makes sense. The default method on the `ZipOutputStream` is only used if the method isn't specified on the `ZipEntry`.
Assuming the following signature
```scala
def makeStored[F[_]: Async](chunkSize: Int = Defaults.defaultChunkSize): ZipArchiver[F, Some] = 
    make[F, Some](ZipOutputStream.STORED, chunkSize)
```
Then the following program will not compile, even though it's a valid program, i.e. the underlying `java.util.ZipOutputStream` will be happy to accept the entries. 

```scala
  /** Create an ArchiveEntry with a known size of an already compressed stream, i.e. ZipEntry.STORED
    */
  def storedEntry[F[_]](size: Long, name: String, stream: Stream[F, Byte]): ArchiveEntry[Some, ZipEntry] = {
    val zipEntry = new ZipEntry(name)
    zipEntry.setSize(size)
    zipEntry.setMethod(ZipEntry.STORED)
    ArchiveEntry[Some, ZipEntry](name = name, uncompressedSize = Some(size), underlying = zipEntry)
  }

  /** Create an ArchiveEntry with an unknown size of a stream that needs to be compressed, i.e. ZipEntry.DEFLATED
    */
  def deflatedEntry[F[_]](name: String, stream: Stream[F, Byte]): ArchiveEntry[Option, ZipEntry] = {
    val zipEntry = new ZipEntry(name)
    zipEntry.setMethod(ZipEntry.DEFLATED)
    ArchiveEntry[Option, ZipEntry](name = name, underlying = zipEntry)
  }

  // We have some exiting compressed data from somewhere
  val existingCompressedData: Stream[IO, (Long, String, Stream[IO, Byte])] = ???
  // We also have some data that needs to be compressed and we don't know the size
  val toCompressData: Stream[IO, (String, Stream[IO, Byte])] = ???

  // All our entries
  val archiveEntries: Stream[IO, ArchiveEntry[Option, ZipEntry]] =
    existingCompressedData.map { case (size, title, data) => storedEntry(size, title, data) } ++
      toCompressData.map { case (title, data) => deflatedEntry(title, data) }

  val zipArchiver = ZipArchiver.makeStored[IO]()
  val compressedData: Stream[IO, Byte] = archiveEntries.through(zipArchiver.archive)
```

**Comment by jakobmerrild** [comment]
But maybe this is a bit of a contrived example, it *would* compile by using the suggested `ZipArchiver.makeDeflated` factory method

**Comment by lhns** [comment]
Thanks for the changes! Shouldn't we just deprecate the old make method?

**Comment by jakobmerrild** [comment]
@lhns Thanks for accepting my PRs. Any chance for a `2.2.0` release, we need the changes in this PR to use your library as we are wanting to create Zip archives from streams of data of unknown size :)

**Comment by lhns** [comment]
@jakobmerrild, sure I just released this in [v2.2.0](https://github.com/lhns/fs2-compress/releases/tag/2.2.0)

**Pull request merged**
