### PR TITLE
Add brotli compressor

### PR DESCRIPTION
**Pull request by jakobmerrild**
Solves https://github.com/lhns/fs2-compress/issues/105

Unsure if you want a dependency on https://github.com/hyperxpro/Brotli4j, but it seems like the goto JVM implementation.

### CODE REVIEW

**Comment by lhns** [comment]
Should we keep a module with org.brotli % dec like with zip and zip4j? brotli dec seems to be the official decoder implementation and might be interesting to use for performance or correctness reasons. Or do you think that would be overkill?

**Comment by jakobmerrild** [comment]
We can certainly do that. I'll leave it up to you to decide. 
Support for encoding is likely not going to happen with the official package given that this issue is 8 years old: https://github.com/google/brotli/issues/405

**Comment by lhns** [comment]
That's true but for http clients, which are probably the common use-case for brotli, only decoding is needed. I think we should have two modules.

**Comment by jakobmerrild** [comment]
Closed in favor of #152

**Pull request closed without merging**
